services:
  - type: web
    name: archivr
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npx prisma db push --accept-data-loss && node .next/standalone/server.js
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        value: file:/var/data/custom.db
      - key: HOSTNAME
        value: "0.0.0.0"
    disk:
      name: archivr-data
      mountPath: /var/data
      sizeGB: 1
